-- Create tables
CREATE TABLE IF NOT EXISTS URL (
    url_key VARCHAR(20) PRIMARY KEY,
	custom_key VARCHAR(20),
    url VARCHAR(1024) NOT NULL,
    created_on TIMESTAMP NOT NULL
);
CREATE SEQUENCE URL_SEQUENCE MINVALUE 1 MAXVALUE 525649985 INCREMENT BY 1 START WITH 267473598 NOCACHE NOCYCLE;
