-- Create tables
CREATE TABLE IF NOT EXISTS URL (
    url_key VARCHAR(20) PRIMARY KEY,
	custom_key VARCHAR(20),
    url VARCHAR(1024) NOT NULL,
    created_on TIMESTAMP NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS URL_SEQUENCE
    START WITH 267473598
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE;